Repository conjure-cp/conjure-oxide, pull requests merged in 2024-04, with the labels that each got.

#258 Improved Metrics for Code Coverage Deploy
  .github/workflows/code-coverage-deploy.yml
  .github/workflows/docs.yml
  .github/workflows/test.yml
  tools/code-coverage-diff/calculate_coverage_difference.py
  tools/code-coverage-diff/requirements.txt
Labels: area::conjure-oxide, area::ci

#287 Rewriter Optimization
  .gitignore
  conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/01/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/01/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/02/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/02/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/03/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/03/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/04/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/04/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/05/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/05/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/xyz/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/xyz/input.expected-rewrite.serialised.json
  conjure_oxide/tests/plot_rewriter_optimization_performance.py
  conjure_oxide/tests/rewrite_tests.rs
  crates/conjure_core/src/ast/expressions.rs
  crates/conjure_core/src/metadata.rs
  crates/conjure_core/src/rule_engine/rewrite.rs
  crates/conjure_core/src/stats/mod.rs
  crates/conjure_core/src/stats/rewriter_stats.rs
Labels: area::conjure-oxide

#292 Some fixes to Optimisation
  conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/bool/03/bool-03.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/div/01/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/div/01/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/div/02/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/div/02/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/div/03/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/div/03/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/div/04/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/div/04/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/div/05/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/div/05/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/01/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/01/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/02/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/02/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/03/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/03/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/04/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/04/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/basic/min/05/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/basic/min/05/input.expected-rewrite.serialised.json
  conjure_oxide/tests/integration/xyz/input.expected-parse.serialised.json
  conjure_oxide/tests/integration/xyz/input.expected-rewrite.serialised.json
  crates/conjure_core/src/ast/expressions.rs
  crates/conjure_core/src/ast/mod.rs
  crates/conjure_core/src/ast/types.rs
  crates/conjure_core/src/metadata.rs
  crates/conjure_core/src/rule_engine/rewrite.rs
  crates/conjure_core/src/rule_engine/rule.rs
  crates/conjure_core/src/rules/base.rs
  crates/conjure_core/src/rules/minion.rs
Labels: help wanted
